run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - errcheck
    - gocritic
    - gosimple
    - typecheck
  disable:
    - depguard
    - lll
    - funlen
    - cyclop

linters-settings:
  goimports:
    local-prefixes: gothicforge3
  revive:
    severity: warning
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers": false]
  gocritic:
    disabled-checks:
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gomnd
  max-same-issues: 3
  max-issues-per-linter: 0
