// Code generated by templ - DO NOT EDIT.

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AuthRegister renders the registration form page.
func AuthRegister() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mx-auto max-w-7xl px-4 md:px-6\"><div class=\"navbar bg-base-100/60 backdrop-blur rounded-box mt-4 border border-white/15 shadow-xl ring-1 ring-white/10\"><div class=\"navbar-start\"><a href=\"/\" class=\"btn btn-ghost text-xl\">Gothic Forge</a></div><div class=\"navbar-center hidden md:flex\"></div><div class=\"navbar-end\"><a class=\"btn btn-ghost\" href=\"/auth/login\">Sign in</a></div></div><section class=\"pt-16 pb-12 md:pt-20 md:pb-16 grid place-items-center\"><div class=\"card bg-base-200/60 border border-white/10 rounded-box shadow-xl ring-1 ring-white/10 w-full max-w-md\"><div class=\"card-body\"><h1 class=\"card-title text-2xl\">Create account</h1><form class=\"form-control mt-6 grid gap-4\" hx-post=\"/auth/register\" hx-swap=\"none\"><label class=\"input input-bordered flex items-center gap-2\"><input type=\"email\" name=\"email\" class=\"grow\" placeholder=\"Email\" required></label> <label class=\"input input-bordered flex items-center gap-2\"><input type=\"password\" name=\"password\" class=\"grow\" placeholder=\"Password (min 8 chars)\" minlength=\"8\" required></label> <button class=\"btn btn-primary\" type=\"submit\">Register</button><div class=\"text-sm opacity-80\">Already have an account? <a class=\"link\" href=\"/auth/login\">Sign in</a></div></form></div></div></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = LayoutSEO(MergeWithDefaults(SEO{
			Title:     "Register",
			Canonical: "/auth/register",
		})).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
