name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Generate templates (templ)
        run: go run github.com/a-h/templ/cmd/templ@latest generate -include-version=false -include-timestamp=false
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download deps
        run: go run ./cmd/gforge mod download
      - name: Vet
        run: go run ./cmd/gforge vet
      - name: Test
        run: go run ./cmd/gforge test
      - name: CLI Test (gforge)
        run: go run ./cmd/gforge test --with-build --cover
        env:
          LOG_FORMAT: off
          GFORGE_SKIP_TOOLS: "1"
      - name: Govulncheck
        run: go run ./cmd/gforge vuln
      - name: Deploy dry-run smoke
        run: go run ./cmd/gforge deploy --dry-run
        env:
          GFORGE_SKIP_TOOLS: "1"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Generate templates (templ)
        run: go run github.com/a-h/templ/cmd/templ@latest generate -include-version=false -include-timestamp=false
      - name: golangci-lint (gforge)
        run: go run ./cmd/gforge lint --args "--timeout=5m"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-test, lint]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Download deps
        run: go mod download
      - name: Export static site (SSG)
        run: go run ./cmd/gforge export -o dist
        env:
          GFORGE_SKIP_TOOLS: "1"
          LOG_FORMAT: off
      - name: Run DB migrations (Neon)
        if: ${{ env.DATABASE_URL != '' }}
        run: go run ./cmd/gforge db --migrate
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
      - name: Deploy to Cloudflare Pages
        if: ${{ env.CF_API_TOKEN != '' && env.CF_ACCOUNT_ID != '' && env.CF_PROJECT_NAME != '' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ env.CF_API_TOKEN }}
          accountId: ${{ env.CF_ACCOUNT_ID }}
          projectName: ${{ env.CF_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ env.GITHUB_TOKEN }}
      - name: Install Railway CLI
        if: ${{ env.RAILWAY_TOKEN != '' }}
        run: |
          sudo curl -fsSL -o /usr/local/bin/railway https://github.com/railwayapp/cli/releases/latest/download/railway-linux-amd64
          sudo chmod +x /usr/local/bin/railway
          railway --version
      - name: Railway deploy (up)
        if: ${{ env.RAILWAY_TOKEN != '' }}
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}
